### ISSUE TITLE
Backblaze S3 error when backing up volumes

### ISSUE THREAD

**Issue by bymayo** [weareferal/craft-remote-backup#21]
We're hitting and error when trying to backup the volume using the CLI. The error seems to be a 500 one connecting to Backblaze.

I checked the troubleshooting (https://github.com/weareferal/craft-remote-backup/wiki/Backblaze-B2#troubleshooting) and checked the credentials but they all seem fine. 

I can backup databases, just not volumes.

```
Next Aws\S3\Exception\S3Exception: Error executing "PutObject" on "https://website-co-uk.s3.us-west-002.backblazeb2.com/website_production_200730_091903_mo9nzhnl1f_v3.4.19.zip"; AWS HTTP error: Server error: `PUT https://website-co-uk.s3.us-west-002.backblazeb2.com/website_production_200730_091903_mo9nzhnl1f_v3.4.19.zip` resulted in a `500 Internal Server Error` response:
{
  "code": "internal_error",
  "message": "incident id 199ec4f89122-40f425ccaab81307",
  "status": 500
}
 Unable to parse error information from response - Error parsing XML: String could not be parsed as XML in /var/www/vhosts/website.co.uk/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195
```

**Comment by timmyomahony** [comment]
Hey @bymayo that’s strange that you can backup the database OK but not the volumes (as you mentioned - credentials must be OK).

What size is the volume backup? I wonder if it’s related to being particularly large? Was it workin at any point? I assume it doesn’t work from the control panel UI either?

The 500 error from B2 would suggest it’s an issue on their end but it might also be a bug with the zip file that is created

**Comment by timmyomahony** [comment]
Also the “Error parsing XML” part of the message is actually a red herring I think. That’s an error message from the plugin trying to read the error response from the AWS PHP library/B2.

**Comment by timmyomahony** [comment]
Also, what region are you backing up to? I wonder if it’s specific to that region?

**Comment by bymayo** [comment]
I did think it could be due to the size of the file. It's likely this one could be very large! As there are a lot of assets.

This is the first time I've used the plugin so it's just not working from the off. In the CP it just seems to hang, and then I get the same error in the `web.log` file.

The region is `us-west-002`

If it is due to the size, would it be better if the assets were optional, and could be split in to a separate zip?

**Comment by timmyomahony** [comment]
Thanks for the update. I'm trying to replicate this locally with B2 in the same region. Going to push a potential fix with more logging for further debugging.

**Comment by bymayo** [comment]
@timmyomahony Sounds good!

After a few of our sites got hacked recently due to SEOmatic having a flaw and requiring an update we've been looking at options for disaster recovery. This plugin plays a part of it!

**Comment by timmyomahony** [comment]
I'm not sure why I didn't reply to this issue @bymayo , apologies. I recently made some updates (1.4.0) to the plug-in that hopefully address this issue (along with others).

**Comment by timmyomahony** [comment]
I'm closing this but happy to reopen if this is still an issue after the previous updates.
