### ISSUE TITLE
Make cron requirement more obvious

### ISSUE THREAD

**Issue by timmyomahony** [weareferal/craft-remote-backup#24]
Either via the UI or just the docs. It's easy to miss that you need to manually automate the backups via Cron

**Comment by timmyomahony** [comment]
Added in 1.4.0 https://github.com/weareferal/craft-remote-backup/commit/28d5f5ebc78cad391ab92b4cdce802d117bae904

**Comment by MattAppleton** [comment]
a few example cron scripts would be helpful :)
