### ISSUE TITLE
Clarify pruning options

### ISSUE THREAD

**Issue by fthues** [weareferal/craft-remote-backup#27]
We want to keep the 3 latest backups only.

According to the docs the plugin will keep:

>     The 6 most recent hourly backups
>     The 14 most recent daily backups
>     The earliest backups of the 4 most recent weeks
>     The earliest backups of the 6 most recent months
>     The earliest backups of the 3 most recent years

What makes a backup an "hourly" or "daily" backup?

**Comment by fthues** [comment]
Nevermind, I _think_ I get it now after browsing the service code:

It looks at all existing backups and puts them into five independent "buckets" (arrays), partitioned by hour/day/week/month/year (determined by each backup's date). Then each bucket is truncated to its respective maximum length as defined in the settings. Any backups that "survive" this operation (are still referenced in at least one of the buckets) are kept.

**Comment by timmyomahony** [comment]
Hi @fThues yes exactly. I'll be revisiting this algorithm as it's a pretty simple implementation. How the backups are pruned is separate to how often you backup via cron (or manually). I have always set the backup to run hourly, followed by a pruning.
