### ISSUE TITLE
Error Fetching Database

### ISSUE THREAD

**Issue by damienbuckley** [weareferal/craft-remote-backup#28]
Just installed with Craft v3.6.1, set up per instructions for Amazon S3 but getting these errors - both local and production
<img width="313" alt="Screen Shot 2021-01-29 at 2 12 13 pm" src="https://user-images.githubusercontent.com/728153/106231035-7119ad00-623c-11eb-9297-1f768e747128.png">

**Comment by timmyomahony** [comment]
Hi @damienbuckley have you looked in `storage/logs/web.log`? You should see an error there when you try load that page. It's likely an issue with the connection details for the bucket not being accessible

**Comment by damienbuckley** [comment]
My bad - I didn’t install the SDK 😬

Works perfectly, thanks
