### ISSUE TITLE
Remote Backup Location not Working since Updating to Craft 

### ISSUE THREAD

**Issue by danleecpi** [weareferal/craft-remote-backup#29]
Since updating Craft CMS to the latest version I noticed that our uploaded files get backed-up daily to temporary storage. Uploaded asset files live on DigitalOcean Spaces so we have no need to back up these files to the same server Craft CMS resides on.

- All asset files are stored daily in a new folder. Example path: `storage/runtime/temp/tfxrsolmuf/images`
- This caused us to go over our allotted disk space and cause the server to go down
- The backup is happening daily
- Using Craft 3.6.11.1
- Using Remote Backup 1.4.0
- We use the DigitalOcean spaces volume plugin

**How I have temporarily fixed the issue.**

I have disabled the last two lines in the remote-backup.sh script

```
#! /bin/bash

# A simple script that uses craft-remote-backup
/home/forge/www.uk-cpi.com/craft remote-backup/database/create
/home/forge/www.uk-cpi.com/craft remote-backup/database/prune
# /home/forge/www.uk-cpi.com/craft remote-backup/volume/create
# /home/forge/www.uk-cpi.com/craft remote-backup/volume/prune
```

I _think_ ultimately there seems to be a connection issue with our remote storage location that caused the files to be backed up into the temporary storage folder.

[![enter image description here][1]][1]

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/zbtoo.png
  [2]: https://i.stack.imgur.com/rTFhZ.png

**Comment by timmyomahony** [comment]
Hey @danleecpi sorry for the delay. I'll look into this ASAP. The file should be backing up locally to the temp folder before being uploaded to the remote location. But usually they should be deleted from here _unless_ you have the `keepLocal` setting enabled. In other words, it seems like the files aren't being deleted after upload to your remote location.

Are the files getting sent to the remote location at all? As you said, it sounds like this might be the problem (the upload is failing).

Either way, I think it makes sense here for the temporary files to _always_ be deleted, regardless if the upload fails.

**Comment by danleecpi** [comment]
Thanks for the reply @timmyomahony and sorry for the delay in responding.

For now, I have isolated the crone job connected with backing up the volumes.

Commenting out the following stops the daily backup.

```
# /home/forge/www.example.com/craft remote-backup/volume/create
# /home/forge/www.example.com/craft remote-backup/volume/prune
```

As you indicate I think there is an issue with uploading to the remote storage location. Database backups are working fine, however:

<img width="690" alt="Screenshot 2021-04-13 at 09 51 10" src="https://user-images.githubusercontent.com/59832142/114525170-c9f2c200-9c3d-11eb-9664-9d171747fd47.png">

Do you have any idea why an upload would fail?

**Comment by timmyomahony** [comment]
Hi @danleecpi  I dropped the ball on this issue so apologies 😬. It has been a challenge to manage the plugins alongside client work (not an excuse, just an explanation). I'm getting back on top of everything and have a recent Craft 4 update. Let me know if you stuck with the plugin (and whether this issue got sorted). If not, I'd be happy to sort you out with a free license if you want to try it out again on a project.

**Comment by timmyomahony** [comment]
Hi @danleecpi not sure if you've moved on from this plugin, but just a note that there's a new version here that will make handling failed uploads better (any temp files that were created will be cleared on failure):

https://github.com/weareferal/craft-remote-backup/releases/tag/4.1.0

I've also got a number of new features planned to make dealing with larger files easier. I'm going to close this issues for the moment, but if you are still using the plugin and having issues please reach out and I'll follow up.
