### ISSUE TITLE
FR: Settings to hide Database or Volume Backups

### ISSUE THREAD

**Issue by chadcrowell** [weareferal/craft-remote-backup#3]
Our assets are hosted on S3/Cloudfront already and there's never going to be a need to backup volumes, only databases. It would be great if there were a lightswitch in the plugin settings to hide volume syncing, so that on the utility page, only the database part of the UI shows. May as well add one for databases, too, incase someone only wants to be able to backup volumes.

**Comment by timmyomahony** [comment]
Good idea, that should be easy to implement

**Comment by timmyomahony** [comment]
Just added a quick update to enable this https://github.com/weareferal/craft-remote-backup/pull/6
