### ISSUE TITLE
Google Drive Auth URL not found

### ISSUE THREAD

**Issue by ghost** [weareferal/craft-remote-backup#30]
On my local website when I input the data needed for the Remote Sync config and hit 'Authenticate with Google Drive'.
![image](https://user-images.githubusercontent.com/93604018/156028841-a734deff-def9-4cac-9f9b-dfa133ad35f4.png)

I am greeted by a 
![image](https://user-images.githubusercontent.com/93604018/156028969-6fd2f3fd-8140-44e2-9d10-d5daadf2f198.png)

When I try to do this on the Staging site I successfully get to the Google Auth page which tells my my data is correct but after I click allow I get a craft template error saying /admin/remote-sync/google-drive/auth isn't a template. 

It sounds like the plugin isn't creating some needed pages. 

I am eager to get this working so I can get all my databases synced up and then purchase this plugin. 

Let me know if there is any information you need for this. 

Cheers,

Oscar

**Comment by timmyomahony** [comment]
Hi @OscarDiva I dropped the ball on this issue so apologies 😬. It has been a challenge to manage the plugins alongside client work (not an excuse, just an explanation). I'm getting back on top of everything and have a recent Craft 4 update. Let me know if you stuck with the plugin and if this is still an issue? I was testing Google Drive myself as part of the update and can confirm it's technically working, so it might just be a configuration issue with the host name.

**Comment by timmyomahony** [comment]
I'm going to close this issue now, but if it's still a problem please leave a comment and I'll re-open.
