### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by andypullen** [weareferal/craft-remote-backup#31]
I'd assume this is in the same position as [craft-remote-sync](https://github.com/weareferal/craft-remote-sync), along with https://github.com/weareferal/craft-remote-sync/issues/46, but thought I'd open an issue here too in case not. Thanks.

**Comment by timmyomahony** [comment]
Thanks @andypullen support for 4 is on the way. I had made a push to get it out-the-door but unfortunately there's been changes with the filesystem and assets in Craft 4 that put a spanner in the works. I'm going to get stuck back in next week to finally get a release out. Thanks for the patience 😬

**Comment by timmyomahony** [comment]
OK, I was able to sort out the issues with the filesystem changes, so 4.0.0 should finally be here. You can see the release:

https://github.com/weareferal/craft-remote-sync/releases/tag/4.0.0

Check it out and let me know how you get on.
