### ISSUE TITLE
Dropbox backups are unusable right now

### ISSUE THREAD

**Issue by Gaspadlo** [weareferal/craft-remote-backup#34]
Dropbox has switched to short-live access tokens (needed to be periodically refreshed).
Since Frebruary - March 2022 there is no way to generate persistent/long-lived access token.

**Comment by timmyomahony** [comment]
Thanks @Gaspadlo for this. Unfortunately I'll just have to disable it for the moment until I can add a full oAuth flow (I've removed Dropbox from the settings in 4.1.0). Thankfully I should be able to do this with the current plugin structure. I'm tracking this here on the `remote-core` module so I'm going to close this one.

https://github.com/weareferal/craft-remote-core/issues/15
