### ISSUE TITLE
Backups failing

### ISSUE THREAD

**Issue by josh-attwood** [weareferal/craft-remote-backup#35]
We're having an issue which is stopping backups from running and is keeping the temp files inside storage which is quickly filling up our server.

The logs show an error below which I can replicate when running a backup through the CLI.

Failed to open stream: Too many open files

**Comment by timmyomahony** [comment]
Hi @josh-attwood I imagine this is an issue backing up assets as opposed to database? Are your assets remote? Either way, it sounds like it might be related to:

https://stackoverflow.com/a/14749074/396300

Could you attach the logs (or send them to me on Discord if you're on it: username `timmy`).

**Comment by josh-attwood** [comment]
Hey @timmyomahony, sent you a couple of messages on discord if you have time to have a look! Thanks

**Comment by timmyomahony** [comment]
Hi @josh-attwood there a new version 4.1.0 now that will hopefully help with larger files. I haven't directly addressed the issues in the logs you reported, as I think those are specific to the machine running the backup.

I have a suspicion that there might be some issues related to how the temporary zip files are created. I'm tracking that here:

- https://github.com/weareferal/craft-remote-core/issues/16

I'm also going to add a CLI command to clear any local backups:

- https://github.com/weareferal/craft-remote-core/issues/17

I've also got plans for email notifications and retries here:

- https://github.com/weareferal/craft-remote-backup/issues/38
- https://github.com/weareferal/craft-remote-backup/issues/37

So all of this should make larger file backups much easier. In the meantime, check out the updates for this version here:

https://github.com/weareferal/craft-remote-backup/releases/tag/4.1.0

and in the changelog.

**Comment by timmyomahony** [comment]
I'm closing this but happy to reopen if this is still an issue after the previous updates.
