### ISSUE TITLE
Backup to Backblaze 

### ISSUE THREAD

**Issue by danleecreates** [weareferal/craft-remote-backup#4]
Ability to backup to Backblaze would be great.
https://www.backblaze.com/b2/cloud-storage.html

**Comment by timmyomahony** [comment]
Looking into it now thanks

**Comment by danleecreates** [comment]
Thanks @timmyomahony !

**Comment by timmyomahony** [comment]
@nearkingdom just finished releasing not 1, not 2 but 3 new providers in version 1.1.0 via https://github.com/weareferal/craft-remote-backup/pull/8 so you should be able to use this with Backblaze B2 now

Check the readme as well as the guide for Backblaze here https://github.com/weareferal/craft-remote-backup/wiki/Backblaze-B2

**Comment by danleecreates** [comment]
@timmyomahony Come on! Yeeesss! Thanks

**Comment by timmyomahony** [comment]
Haha, appreciate the excitement. Let me know how you get on with it and if you encounter any issues
