### ISSUE TITLE
4.1.0 typo/case-sensitive FS issue "RemoteBackupUtility"

### ISSUE THREAD

**Issue by Gaspadlo** [weareferal/craft-remote-backup#40]
Upgrading to the latest version and accessing the plugin dashboard results in an error
![image](https://user-images.githubusercontent.com/4014669/194150309-88cd1d8c-2de7-43b8-8d3e-84e3ce9e76fe.png)

inspecting the actual structure on the server, the folder name is lowercase 
![image](https://user-images.githubusercontent.com/4014669/194150464-d8ebb451-b358-4bed-95e2-760d4ae34a12.png)

renaming the folder results in another error
`Failed to instantiate component or class "weareferal\remotebackup\assets\remotebackuputility\RemoteBackupUtilityAsset"`

downgrading back to 4.0.1 for now

Weareral possibly using a case-insensitive FS? or something else might be causing this?

**Comment by timmyomahony** [comment]
Yep, I think this is an issue with git not renaming a change due to case sensitivity. Could you try version `4.1.1`?

**Comment by Gaspadlo** [comment]
Hello @timmyomahony, I have tried it today again, but unfortunately the problem persists for me... Maybe a clean install of the plugin might be necessary? (I'd rather avoid that).

Running a Ubuntu 22.04.1 LTS on a google VM machine.

**Comment by timmyomahony** [comment]
🤦🏼 I was able to replicate. I think I forgot to rename a path. Strangely it didn't show up while testing.

Either way, I've tried another fix in 4.1.2. Check that out and hopefully it fixes it.

**Comment by Gaspadlo** [comment]
Seems to be working great now. 👏
