### ISSUE TITLE
IAM Instance Profile support

### ISSUE THREAD

**Issue by justinmacleod** [weareferal/craft-remote-backup#44]
Hello,

We are attempting to use this plugin with S3, but we are unable to generate IAM key/secrets. Instead, we must rely upon permissions included in the EC2 instance profile. However, I am unclear how to get remote backup to pick this up. With Craft, we just have to pass empty strings and it will use the instance profile. I have attempted this here but without success.

**Comment by timmyomahony** [comment]
This is merged as of `4.1.6`.  Thanks for the PR! Let me know how you get on with it. You shouldn't need empty strings any more either on the settings page as the access and secret are optional.
