### ISSUE TITLE
Error - Class "Aws\S3\S3Client" not found

### ISSUE THREAD

**Issue by danlakelake** [weareferal/craft-remote-backup#46]
Hi sr, I get that error when I do the connection test for google drive, configure the plugin as the documentation says: https://github.com/weareferal/craft-remote-backup/wiki/Google-Drive
--> Class "Aws\S3\S3Client" not found

**Comment by timmyomahony** [comment]
A quick fix for this is to install `aws/aws-sdk-php` via composer. You shouldn't actually need that package when using Google Drive, but I have a feeling there's an import issue that needs to be resolved.

**Comment by timmyomahony** [comment]
I'm going to close this issue but if you are continuing to have issues please let me know and I'll open it again.

**Comment by bartrylant** [comment]
Hi

I also have thios error when using B2, so maybe it's good to add dependency this when installing the plugin?

**Comment by timmyomahony** [comment]
Hi @bartrylant yes you need to add the AWS dependency when setting up the plug-in. There's a guide here for B2: https://craft-plugins.timmyomahony.com/remote-backup/docs/backblaze
