### ISSUE TITLE
Issues with admin interface since changing configuration to include bucket directory

### ISSUE THREAD

**Issue by jasonmckinney66** [weareferal/craft-remote-backup#47]
First, thanks for the great plugin.

Since updating our configuration to include a bucket directory, the interface can no long list the backups: "Error Fetching Database Backups" - even though the config test passes and backups are generated to the proper folder on S3. This occurs on my local and on our Cloudways server.

Also, the spinner continues in the interface and the job never "completes" in any way (no feedback) even when the backup is complete. Not sure if these issues are related. We are not using queuing. 

Happy to share our configuration although we used the policy from the docs and the backups are being generated in the proper location. We are running the latest version in Craft CMS 4.5.5

Thanks,

J

**Comment by jasonmckinney66** [comment]
Actually, I'm now getting an error when testing the configuration, "undefined array key 2" if that helps. Thanks.

**Comment by timmyomahony** [comment]
Hi @jasonmckinney66 just to confirm: does the path you are using in the "S3 bucket path" start or end with a slash? If so, that might be causing the issue. The value you use in the setting [shouldn't begin or end with a slash](https://github.com/weareferal/craft-remote-backup/wiki/Amazon-S3#optional-bucket-folder-path).

If that's OK, it might be best to have a closer look at the `web.log`. Would you be able to share that with me via email?

**Comment by jasonmckinney66** [comment]
The issue is a difference in permissions between the plugin and S3 and pertains to directories created within a bucket. If we just add a pathname to the plugin settings, the plugin will create the directory in S3 and the issue is resolved. Thank you for your help diagnosing this.
