### ISSUE TITLE
Regex failing if system name includes periods 

### ISSUE THREAD

**Issue by john-henry** [weareferal/craft-remote-backup#49]
My System Name is A.B.C. Company

regex fails to match, hence errors with listing backups, etc 

![image](https://github.com/weareferal/craft-remote-backup/assets/44709/e7f488b0-2071-4e9a-bc5d-9f30112da3a6)

**Comment by timmyomahony** [comment]
Hi @john-henry thanks for investigating. I assume it's the dots in the name that's causing the issue? I'll update the regex

**Comment by john-henry** [comment]
@timmyomahony Yes the dots. Thanks!

**Comment by john-henry** [comment]
Any luck with this one?

**Comment by timmyomahony** [comment]
Sorry @john-henry for the delay. I have a fix for this, just haven't released yet. Will be reviewing in the next few days as it's a recurring issue.

**Comment by timmyomahony** [comment]
@john-henry I've just pushed a new version `4.1.6` that relaxes the regex and should fix this issue. I'm going to close this but if the problem crops up again let me know and I'll reopen.
