### ISSUE TITLE
Backup to Google Drive

### ISSUE THREAD

**Issue by teamcrisis** [weareferal/craft-remote-backup#5]
A backup option to Google Drive would be much appreciated.

**Comment by timmyomahony** [comment]
Good idea, I'm going to look into this

**Comment by timmyomahony** [comment]
@teamcrisis  just finished releasing Google Drive support in version 1.1.0 via https://github.com/weareferal/craft-remote-backup/pull/8 so you should be able to use this now.

Check the readme as well as the guide for Backblaze here https://github.com/weareferal/craft-remote-backup/wiki/Google-Drive
