### ISSUE TITLE
Plugin trying to delete local backups even though they don't exist

### ISSUE THREAD

**Issue by john-henry** [weareferal/craft-remote-backup#52]
I have Keep Local Backups set to OFF
Cron is running, creating and pruning DBs in AWS with no problems.

However, I am getting logs of errors where it is trying to delete the local databases in `storage/remote-backup `but these don't exist as I have the setting above turned off.

Latest Craft and plugin

**Comment by timmyomahony** [comment]
A local backup is always _created_ when backing up, before being sent to the remote server. The "keep local backups" feature just tracks whether or not to keep that local backup once it's uploaded, or delete it.

It sounds like the plugin it attempting to delete an already-deleted file? Would you be able to send on an example log file with the issue (can send to hey at timmyomahony.com)

**Comment by john-henry** [comment]
The PR here would fix this for me https://github.com/timmyomahony/craft-remote-core/pull/25

**Comment by timmyomahony** [comment]
Apologies for the delay @john-henry. That PR is merged as of the latest Craft 5 version which I've just released.
