### ISSUE TITLE
S3 returns prefix as a separate file

### ISSUE THREAD

**Issue by jcdarwin** [weareferal/craft-remote-backup#54]
My `S3 Bucket Name` is defined as `craft-5adayeducation`, and my `S3 Bucket Path` is defined as `remotebackup`, but when I perform the "Test Connection" it fails because -- although I only have one file in my bucket (`upgrade.5adayeducation.org.nz__production__231218_110657__nixsjmjmml__v4.5.13.sql`)  it returns two entries in `$response['Contents']`:

```
[
    {
        "Key": "remotebackup/",
        "LastModified": "2023-10-22 00:16:12.000000",
        "timezone_type": 2,
        "timezone": "Z",
        "ETag": "d41d8cd98f00b204e9800998ecf8427e",
        "Size": "0",
        "StorageClass": "GLACIER",
        "Owner": {
            "DisplayName": "mebooks.support",
            "ID": "51a1119ec3b864ef78e705b1d7de4d9ba6c248bcac06b5515573cf62b9c546ad"
        }
    },
    {
        "Key": "remotebackup/upgrade.5adayeducation.org.nz__production__231218_110657__nixsjmjmml__v4.5.13.sql",
        "LastModified": "2023-12-18 10:30:34.000000",
        "timezone_type": 2,
        "timezone": "Z",
        "ETag": "3c548f264b353f2730410f631e18d8fb",
        "Size": "281702",
        "StorageClass": "STANDARD",
        "Owner": {
            "DisplayName": "mebooks.support",
            "ID": "51a1119ec3b864ef78e705b1d7de4d9ba6c248bcac06b5515573cf62b9c546ad"
        }
    },
]
```

As you can see from the above, it returns an entry for `remotebackup/` -- this causes a failure in the constructor in `RemoteFile.php` as it doesn't match to `$regex`.

For the sake of the Test Connection, It's possible to work around it by changing:

```
// AWSProvider.php
        foreach ($files as $file) {
            array_push($remote_files, new RemoteFile(basename($file['Key']), $file['Size']));
        }
```

to 

```
// AWSProvider.php
        foreach ($files as $file) {
            if ($file['Size'] != "0") {
                array_push($remote_files, new RemoteFile(basename($file['Key']), $file['Size']));
            }
        }
```

however, there's other logic in this plugin that breaks because of  this issue (e.g. when visiting `admin/utilities/remote-backup`).

Can changes be made to cope with S# returning the prefix as a separate file?

**Comment by timmyomahony** [comment]
Hi @jcdarwin thanks for reporting - let me look into it and I'll follow up

**Comment by jcdarwin** [comment]
Actually, the more accurate fix would be to change:

```
// AWSProvider.php
        foreach ($files as $file) {
            array_push($remote_files, new RemoteFile(basename($file['Key']), $file['Size']));
        }
```

```
// AWSProvider.php
        foreach ($files as $file) {
            if ($file['StorageClass'] == "STANDARD") {
                array_push($remote_files, new RemoteFile(basename($file['Key']), $file['Size']));
            }
        }
```

This ensures that we're only targeting recent files (i.e. StorageClass == "STANDARD"), as the bucket may (as it does in this case) have a policy of moving older files to glacier storage (i.e. StorageClass == "GLACIER")

**Comment by timmyomahony** [comment]
Thanks for this and for the PR, it's very useful. I'll look at merged asap.

**Comment by timmyomahony** [comment]
Apologies for the delay in getting this sorted, I've added these changes as part of [the latest Craft 5 release.](https://github.com/timmyomahony/craft-remote-backup/releases/tag/5.0.0)
