### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by KevinBodi** [weareferal/craft-remote-backup#57]
Will this plugin support Craft 5?

**Comment by john-henry** [comment]
Hi @timmyomahony any timeline for Craft 5 version update?

**Comment by timmyomahony** [comment]
On the way, hopefully in June. Apologies for lack of responses to date, more consistent dev will be happening again this month.

**Comment by john-henry** [comment]
No problems @timmyomahony Enjoy the sunshine and bank holiday

**Comment by marten-wirelab** [comment]
Any update on this?

**Comment by timmyomahony** [comment]
A big apology for the delay in getting this released. I've had an unusually busy year this year having moved country a few months ago, meaning development on Craft plugins has been really slow. Getting back up to speed now and finally have a Craft 5 release that I've just published. You should be able to update to version `5.0.0` now. 

Any issues please let me know and thanks for the understanding.
