### ISSUE TITLE
Error log noise: "Deleting local database zip file"

### ISSUE THREAD

**Issue by tremby** [weareferal/craft-remote-backup#59]
We're logging errors to an aggregator, and we are getting a lot of noise with `Deleting local database zip file:/...` messages.

It appears to come from vendor/weareferal/remote-core/src/services/ProviderService.php line 129.

I haven't dug deep by any means, but on the surface it looks like it's checking whether we wanted to keep the local file or not, and if not, deleting it. This seems like totally expected behaviour so I'm not sure why it would be logged as an error. Perhaps a mistake?

**Comment by timmyomahony** [comment]
Thanks for the help with this, it should be cleaned up in [version `5.0.0`](https://github.com/timmyomahony/craft-remote-backup/releases/tag/5.0.0)
